Repository neo4j/docs-graphql, pull requests merged in 2024-10, with the labels that each got.

#180 Updates to filtering page
  modules/ROOT/pages/queries-aggregations/filtering.adoc
Labels: 5.x, 6.x

#190 automatic cherry-picking
  .backportrc.json
  .github/workflows/auto-backport.yml
Labels: auto-cherry-pick, auto-cherry-pick-to-6.x

#188 Update examples with `@node` directive
  modules/ROOT/pages/directives/autogeneration.adoc
  modules/ROOT/pages/directives/custom-directives.adoc
  modules/ROOT/pages/directives/custom-logic.adoc
  modules/ROOT/pages/directives/database-mapping.adoc
  modules/ROOT/pages/directives/indexes-and-constraints.adoc
  modules/ROOT/pages/directives/schema-configuration/field-configuration.adoc
  modules/ROOT/pages/directives/schema-configuration/global-configuration.adoc
  modules/ROOT/pages/directives/schema-configuration/type-configuration.adoc
  modules/ROOT/pages/driver-configuration.adoc
  modules/ROOT/pages/getting-started/index.adoc
  modules/ROOT/pages/getting-started/toolbox.adoc
  modules/ROOT/pages/integrations/apollo-federation.adoc
  modules/ROOT/pages/integrations/relay-compatibility.adoc
  modules/ROOT/pages/migration/index.adoc
  modules/ROOT/pages/mutations/create.adoc
  modules/ROOT/pages/mutations/delete.adoc
  modules/ROOT/pages/mutations/update.adoc
  modules/ROOT/pages/ogm/directives.adoc
  modules/ROOT/pages/ogm/installation.adoc
  modules/ROOT/pages/ogm/reference.adoc
  modules/ROOT/pages/ogm/selection-set.adoc
  modules/ROOT/pages/ogm/subscriptions.adoc
  modules/ROOT/pages/ogm/type-generation.adoc
  modules/ROOT/pages/queries-aggregations/aggregations.adoc
  modules/ROOT/pages/queries-aggregations/filtering.adoc
  modules/ROOT/pages/queries-aggregations/pagination/cursor-based.adoc
  modules/ROOT/pages/queries-aggregations/pagination/offset-based.adoc
  modules/ROOT/pages/queries-aggregations/queries.adoc
  modules/ROOT/pages/queries-aggregations/sorting.adoc
  modules/ROOT/pages/security/authentication.adoc
  modules/ROOT/pages/security/authorization.adoc
  modules/ROOT/pages/security/impersonation-and-user-switching.adoc
  modules/ROOT/pages/security/operations.adoc
  modules/ROOT/pages/security/subscriptions-authorization.adoc
  modules/ROOT/pages/subscriptions/events.adoc
  modules/ROOT/pages/subscriptions/filtering.adoc
  modules/ROOT/pages/subscriptions/getting-started.adoc
  modules/ROOT/pages/troubleshooting.adoc
  modules/ROOT/pages/types/interfaces.adoc
  modules/ROOT/pages/types/relationships.adoc
  modules/ROOT/pages/types/scalar.adoc
  modules/ROOT/pages/types/spatial.adoc
  modules/ROOT/pages/types/temporal.adoc
  modules/ROOT/pages/types/unions.adoc
Labels: 6.x

#196 added section to readme about auto-cherry-pick github action
  README.adoc
Labels: auto-cherry-pick, auto-cherry-pick-to-6.x

#187 Bump minimum versions of Neo4j and Node.js
  modules/ROOT/pages/index.adoc
Labels: 6.x

#189 Remove references to `create` option on `assertIndexesAndConstraints`
  modules/ROOT/pages/directives/indexes-and-constraints.adoc
Labels: 6.x

#186 Remove OGM docs
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/directives/custom-logic.adoc
  modules/ROOT/pages/directives/index.adoc
  modules/ROOT/pages/driver-configuration.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/ogm/directives.adoc
  modules/ROOT/pages/ogm/index.adoc
  modules/ROOT/pages/ogm/installation.adoc
  modules/ROOT/pages/ogm/reference.adoc
  modules/ROOT/pages/ogm/selection-set.adoc
  modules/ROOT/pages/ogm/subscriptions.adoc
  modules/ROOT/pages/ogm/type-generation.adoc
Labels: 6.x

#185 Mutation pages updates
  modules/ROOT/pages/mutations/create.adoc
  modules/ROOT/pages/mutations/delete.adoc
  modules/ROOT/pages/mutations/index.adoc
  modules/ROOT/pages/mutations/update.adoc
  modules/ROOT/pages/queries-aggregations/aggregations.adoc
Labels: auto-cherry-pick, auto-cherry-pick-to-6.x

#195 Update filtering examples by using `_EQ` and add migration guide
  modules/ROOT/pages/migration/index.adoc
  modules/ROOT/pages/mutations/create.adoc
  modules/ROOT/pages/mutations/delete.adoc
  modules/ROOT/pages/mutations/update.adoc
  modules/ROOT/pages/queries-aggregations/filtering.adoc
  modules/ROOT/pages/queries-aggregations/pagination/cursor-based.adoc
  modules/ROOT/pages/queries-aggregations/pagination/offset-based.adoc
  modules/ROOT/pages/queries-aggregations/queries.adoc
  modules/ROOT/pages/security/authorization.adoc
  modules/ROOT/pages/security/operations.adoc
  modules/ROOT/pages/security/subscriptions-authorization.adoc
  modules/ROOT/pages/subscriptions/events.adoc
  modules/ROOT/pages/subscriptions/filtering.adoc
  modules/ROOT/pages/subscriptions/getting-started.adoc
  modules/ROOT/pages/troubleshooting.adoc
  modules/ROOT/pages/types/interfaces.adoc
  modules/ROOT/pages/types/relationships.adoc
  modules/ROOT/pages/types/scalar.adoc
  modules/ROOT/pages/types/spatial.adoc
  modules/ROOT/pages/types/unions.adoc
Labels: 6.x

#200 addendum to mutations pages + other nitpick
  modules/ROOT/pages/deprecations.adoc
  modules/ROOT/pages/mutations/create.adoc
  modules/ROOT/pages/mutations/delete.adoc
  modules/ROOT/pages/queries-aggregations/filtering.adoc
Labels: 5.x

#199 Apply mutation pages PR to 6.x
  modules/ROOT/pages/deprecations.adoc
  modules/ROOT/pages/migration/index.adoc
  modules/ROOT/pages/mutations/create.adoc
  modules/ROOT/pages/mutations/delete.adoc
  modules/ROOT/pages/mutations/index.adoc
  modules/ROOT/pages/mutations/update.adoc
  modules/ROOT/pages/queries-aggregations/aggregations.adoc
  modules/ROOT/pages/queries-aggregations/filtering.adoc
Labels: 6.x

#204 Remove section about mixing PUSH and POP
  modules/ROOT/pages/mutations/update.adoc
Labels: auto-cherry-pick, auto-cherry-pick-to-6.x

#205 Add 6.x to workflows
  .github/workflows/docs-pr-checks.yml
  .github/workflows/docs-teardown.yml
Labels: auto-cherry-pick, auto-cherry-pick-to-6.x

#201 Add breaking changes on migration guide
  modules/ROOT/pages/migration/index.adoc
Labels: 6.x

#192 Update subscriptions docs with 6.x changes
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/directives/schema-configuration/type-configuration.adoc
  modules/ROOT/pages/subscriptions/customize-cdc.adoc
  modules/ROOT/pages/subscriptions/engines.adoc
  modules/ROOT/pages/subscriptions/events.adoc
  modules/ROOT/pages/subscriptions/filtering.adoc
  modules/ROOT/pages/subscriptions/getting-started.adoc
  modules/ROOT/pages/subscriptions/index.adoc
  modules/ROOT/pages/subscriptions/scaling.adoc
Labels: 6.x

#209 Use secret instead of github_token
  .github/workflows/auto-backport.yml
Labels: auto-cherry-pick, auto-cherry-pick-to-6.x

#203 User feedback for subscriptions authorization
  modules/ROOT/pages/security/subscriptions-authorization.adoc
  modules/ROOT/pages/subscriptions/index.adoc
Labels: auto-cherry-pick, auto-cherry-pick-to-6.x
