Repository neo4j/docs-graphql, pull requests merged in 2025-03, with the labels that each got.

#240 constructor features
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/neo4jgraphql-class.adoc
Labels: 5.x, 6.x, auto-cherry-pick, auto-cherry-pick-to-6.x, auto-cherry-pick-to-7.x, 7.x

#239 Update aggregate documentation for 6.x
  modules/ROOT/pages/queries-aggregations/aggregations.adoc
Labels: 6.x, 7.x

#245 cherry-pick authorization docs to 6.x
  modules/ROOT/pages/security/authentication.adoc
  modules/ROOT/pages/security/authorization.adoc
  modules/ROOT/pages/security/operations.adoc
  modules/ROOT/pages/security/subscriptions-authorization.adoc
  modules/ROOT/pages/types/relationships.adoc
  yarn.lock
Labels: 6.x

#253 Update driver-configuration.adoc
  modules/ROOT/pages/driver-configuration.adoc
Labels: auto-cherry-pick-to-6.x, auto-cherry-pick-to-7.x
